### ISSUE TITLE
Enhance Configuration to Enable Voting Features on a Per-Server Basis

### ISSUE THREAD

**Issue by Chenterito** [MrAmos123/Votify#1]
#### **Context:**
Currently, the "Vote" plugin applies voting settings universally to all servers without distinction. While this approach is simplistic, it lacks the granularity some server admins (like me) need, especially when managing multiple servers with different requirements and preferences.

#### **Feature Request:**
I propose enhancing the plugin's configuration to allow voting features to be toggled on a per-server basis. This means server admins could decide which servers allow:
1. Voting for maps.
2. Voting to kick players.
3. Voting to ban players.

#### **Proposed Configuration Structure:**

Below is a suggested configuration format, utilizing a JSON-like structure that defines which servers (by IP and port) have specific voting features enabled:

```json
"VoteServerEnabled": { 
  "VoteBan": [ 
    "127.0.0.1:27017",
    "127.0.0.1:27018",
    "127.0.0.1:27019",
    "127.0.0.1:27020" 
  ],
  "VoteKick": [ 
    "127.0.0.1:27017",
    "127.0.0.1:27018" 
  ],
  "VoteMap": [ 
    "127.0.0.1:27017",
    "127.0.0.1:27020" 
  ],
  "VoteSkip": [ 
    "127.0.0.1:27017",
    "127.0.0.1:27019" 
  ] 
}
```

**Comment by Ayymoss** [comment]
This feature already exists under Disabled Servers, so negate your needed servers. :)
